---
- name: Cisco Config Replace
  hosts: Cisco
  gather_facts: no

  tasks:
# This is elevated enable mode, note that the other script with 'show run' works which also uses
# elevated mode..
  - name: IOS configuration source example
    ios_config:
      backup: yes
      backup_options:
        filename: Mid-backup.txt
    register: backup_contents
    
  - debug:
      msg: "The contents of the config file are {{ lookup('file','backup/Mid-backup.txt') }} "
